/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type skuGetCollectionsOperation } from "./operation";

export type SkuGetCollectionsOperation = typeof skuGetCollectionsOperation;

export type SkuGetCollectionsRequest =
	HttpOperationPreferredRequest<SkuGetCollectionsOperation>;

export type SkuGetCollectionsRequestParts =
	HttpOperationRequestInput<SkuGetCollectionsOperation>;

export type SkuGetCollectionsSuccessResponse =
	HttpOperationSuccessResponse<SkuGetCollectionsOperation>;

export type SkuGetCollectionsResponseStatus =
	HttpOperationResponseStatus<SkuGetCollectionsOperation>;

export type SkuGetCollectionsErrorStatus =
	HttpOperationErrorStatus<SkuGetCollectionsOperation>;

export type SkuGetCollectionsResponseByStatus<
	TStatus extends SkuGetCollectionsResponseStatus =
		SkuGetCollectionsResponseStatus,
> = HttpOperationResponseByStatus<SkuGetCollectionsOperation, TStatus>;

export type SkuGetCollectionsApiError<
	TStatus extends SkuGetCollectionsErrorStatus = SkuGetCollectionsErrorStatus,
> = OperationApiError<SkuGetCollectionsOperation, TStatus>;

export type SkuGetCollectionsErrorResponseBody<
	TStatus extends SkuGetCollectionsErrorStatus = SkuGetCollectionsErrorStatus,
> = HttpOperationErrorBody<SkuGetCollectionsOperation, TStatus>;
