/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type promoListOperation } from "./operation";

export type PromoListOperation = typeof promoListOperation;

export type PromoListRequest =
	HttpOperationPreferredRequest<PromoListOperation>;

export type PromoListRequestParts =
	HttpOperationRequestInput<PromoListOperation>;

export type PromoListSuccessResponse =
	HttpOperationSuccessResponse<PromoListOperation>;

export type PromoListResponseStatus =
	HttpOperationResponseStatus<PromoListOperation>;

export type PromoListErrorStatus = HttpOperationErrorStatus<PromoListOperation>;

export type PromoListResponseByStatus<
	TStatus extends PromoListResponseStatus = PromoListResponseStatus,
> = HttpOperationResponseByStatus<PromoListOperation, TStatus>;

export type PromoListApiError<
	TStatus extends PromoListErrorStatus = PromoListErrorStatus,
> = OperationApiError<PromoListOperation, TStatus>;

export type PromoListErrorResponseBody<
	TStatus extends PromoListErrorStatus = PromoListErrorStatus,
> = HttpOperationErrorBody<PromoListOperation, TStatus>;
