/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type authCheckTokenOperation } from "./operation";

export type AuthCheckTokenOperation = typeof authCheckTokenOperation;

export type AuthCheckTokenRequest =
	HttpOperationPreferredRequest<AuthCheckTokenOperation>;

export type AuthCheckTokenRequestParts =
	HttpOperationRequestInput<AuthCheckTokenOperation>;

export type AuthCheckTokenSuccessResponse =
	HttpOperationSuccessResponse<AuthCheckTokenOperation>;

export type AuthCheckTokenResponseStatus =
	HttpOperationResponseStatus<AuthCheckTokenOperation>;

export type AuthCheckTokenErrorStatus =
	HttpOperationErrorStatus<AuthCheckTokenOperation>;

export type AuthCheckTokenResponseByStatus<
	TStatus extends AuthCheckTokenResponseStatus = AuthCheckTokenResponseStatus,
> = HttpOperationResponseByStatus<AuthCheckTokenOperation, TStatus>;

export type AuthCheckTokenApiError<
	TStatus extends AuthCheckTokenErrorStatus = AuthCheckTokenErrorStatus,
> = OperationApiError<AuthCheckTokenOperation, TStatus>;

export type AuthCheckTokenErrorResponseBody<
	TStatus extends AuthCheckTokenErrorStatus = AuthCheckTokenErrorStatus,
> = HttpOperationErrorBody<AuthCheckTokenOperation, TStatus>;
