/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type usersRegisterDeviceOperation } from "./operation";

export type UsersRegisterDeviceOperation = typeof usersRegisterDeviceOperation;

export type UsersRegisterDeviceRequest =
	HttpOperationPreferredRequest<UsersRegisterDeviceOperation>;

export type UsersRegisterDeviceRequestParts =
	HttpOperationRequestInput<UsersRegisterDeviceOperation>;

export type UsersRegisterDeviceSuccessResponse =
	HttpOperationSuccessResponse<UsersRegisterDeviceOperation>;

export type UsersRegisterDeviceResponseStatus =
	HttpOperationResponseStatus<UsersRegisterDeviceOperation>;

export type UsersRegisterDeviceErrorStatus =
	HttpOperationErrorStatus<UsersRegisterDeviceOperation>;

export type UsersRegisterDeviceResponseByStatus<
	TStatus extends UsersRegisterDeviceResponseStatus =
		UsersRegisterDeviceResponseStatus,
> = HttpOperationResponseByStatus<UsersRegisterDeviceOperation, TStatus>;

export type UsersRegisterDeviceApiError<
	TStatus extends UsersRegisterDeviceErrorStatus =
		UsersRegisterDeviceErrorStatus,
> = OperationApiError<UsersRegisterDeviceOperation, TStatus>;

export type UsersRegisterDeviceErrorResponseBody<
	TStatus extends UsersRegisterDeviceErrorStatus =
		UsersRegisterDeviceErrorStatus,
> = HttpOperationErrorBody<UsersRegisterDeviceOperation, TStatus>;
