/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type promocodesValidateOperation } from "./operation";

export type PromocodesValidateOperation = typeof promocodesValidateOperation;

export type PromocodesValidateRequest =
	HttpOperationPreferredRequest<PromocodesValidateOperation>;

export type PromocodesValidateRequestParts =
	HttpOperationRequestInput<PromocodesValidateOperation>;

export type PromocodesValidateSuccessResponse =
	HttpOperationSuccessResponse<PromocodesValidateOperation>;

export type PromocodesValidateResponseStatus =
	HttpOperationResponseStatus<PromocodesValidateOperation>;

export type PromocodesValidateErrorStatus =
	HttpOperationErrorStatus<PromocodesValidateOperation>;

export type PromocodesValidateResponseByStatus<
	TStatus extends PromocodesValidateResponseStatus =
		PromocodesValidateResponseStatus,
> = HttpOperationResponseByStatus<PromocodesValidateOperation, TStatus>;

export type PromocodesValidateApiError<
	TStatus extends PromocodesValidateErrorStatus = PromocodesValidateErrorStatus,
> = OperationApiError<PromocodesValidateOperation, TStatus>;

export type PromocodesValidateErrorResponseBody<
	TStatus extends PromocodesValidateErrorStatus = PromocodesValidateErrorStatus,
> = HttpOperationErrorBody<PromocodesValidateOperation, TStatus>;
