/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type productsGetSortOptionsOperation } from "./operation";

export type ProductsGetSortOptionsOperation =
	typeof productsGetSortOptionsOperation;

export type ProductsGetSortOptionsRequest =
	HttpOperationPreferredRequest<ProductsGetSortOptionsOperation>;

export type ProductsGetSortOptionsRequestParts =
	HttpOperationRequestInput<ProductsGetSortOptionsOperation>;

export type ProductsGetSortOptionsSuccessResponse =
	HttpOperationSuccessResponse<ProductsGetSortOptionsOperation>;

export type ProductsGetSortOptionsResponseStatus =
	HttpOperationResponseStatus<ProductsGetSortOptionsOperation>;

export type ProductsGetSortOptionsErrorStatus =
	HttpOperationErrorStatus<ProductsGetSortOptionsOperation>;

export type ProductsGetSortOptionsResponseByStatus<
	TStatus extends ProductsGetSortOptionsResponseStatus =
		ProductsGetSortOptionsResponseStatus,
> = HttpOperationResponseByStatus<ProductsGetSortOptionsOperation, TStatus>;

export type ProductsGetSortOptionsApiError<
	TStatus extends ProductsGetSortOptionsErrorStatus =
		ProductsGetSortOptionsErrorStatus,
> = OperationApiError<ProductsGetSortOptionsOperation, TStatus>;

export type ProductsGetSortOptionsErrorResponseBody<
	TStatus extends ProductsGetSortOptionsErrorStatus =
		ProductsGetSortOptionsErrorStatus,
> = HttpOperationErrorBody<ProductsGetSortOptionsOperation, TStatus>;
