/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type favoritesRemoveOperation } from "./operation";

export type FavoritesRemoveOperation = typeof favoritesRemoveOperation;

export type FavoritesRemoveRequest =
	HttpOperationPreferredRequest<FavoritesRemoveOperation>;

export type FavoritesRemoveRequestParts =
	HttpOperationRequestInput<FavoritesRemoveOperation>;

export type FavoritesRemoveSuccessResponse =
	HttpOperationSuccessResponse<FavoritesRemoveOperation>;

export type FavoritesRemoveResponseStatus =
	HttpOperationResponseStatus<FavoritesRemoveOperation>;

export type FavoritesRemoveErrorStatus =
	HttpOperationErrorStatus<FavoritesRemoveOperation>;

export type FavoritesRemoveResponseByStatus<
	TStatus extends FavoritesRemoveResponseStatus = FavoritesRemoveResponseStatus,
> = HttpOperationResponseByStatus<FavoritesRemoveOperation, TStatus>;

export type FavoritesRemoveApiError<
	TStatus extends FavoritesRemoveErrorStatus = FavoritesRemoveErrorStatus,
> = OperationApiError<FavoritesRemoveOperation, TStatus>;

export type FavoritesRemoveErrorResponseBody<
	TStatus extends FavoritesRemoveErrorStatus = FavoritesRemoveErrorStatus,
> = HttpOperationErrorBody<FavoritesRemoveOperation, TStatus>;
