import * as fs from "node:fs";
import * as path from "node:path";

import * as ts from "typescript";

interface OperationTypesTemplate {
	aliasBase: string;
	operationIdentifier: string;
}

interface RenderTypesTemplate extends OperationTypesTemplate {
	httpOperationApiErrorModuleSpecifier: string;
	httpOperationInferenceModuleSpecifier: string;
}

interface OperationStatementsTemplate extends OperationTypesTemplate {
	httpOperationApiErrorModuleSpecifier: string;
	httpOperationInferenceModuleSpecifier: string;
	sourceFile: ts.SourceFile;
}

interface OperationDeclaration {
	initializer: ts.CallExpression;
	name: ts.Identifier;
}

interface GeneratedTypesFile {
	nextContent: string;
	previousContent?: string;
	typesPath: string;
}

const projectRoot = path.resolve(import.meta.dirname, "..");
const apiRoot = path.join(projectRoot, "src", "api");
const httpOperationApiErrorPath = path.join(
	projectRoot,
	"src",
	"http-operation",
	"api-error.ts",
);
const httpOperationInferencePath = path.join(
	projectRoot,
	"src",
	"http-operation",
	"inference.ts",
);
const operationSuffix = "Operation";

function createTypeReference(
	name: string,
	typeArguments: ts.TypeNode[],
): ts.TypeReferenceNode {
	return ts.factory.createTypeReferenceNode(
		ts.factory.createIdentifier(name),
		typeArguments,
	);
}

function createExportedTypeAlias(
	name: string,
	typeNode: ts.TypeNode,
	typeParameters?: ts.TypeParameterDeclaration[],
): ts.TypeAliasDeclaration {
	return ts.factory.createTypeAliasDeclaration(
		[ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
		ts.factory.createIdentifier(name),
		typeParameters,
		typeNode,
	);
}

function createFileHeaderComment(
	sourceFile: ts.SourceFile,
): ts.NotEmittedStatement {
	const headerStatement = ts.factory.createNotEmittedStatement(sourceFile);

	ts.addSyntheticLeadingComment(
		headerStatement,
		ts.SyntaxKind.MultiLineCommentTrivia,
		[
			"*",
			" * This file is auto-generated by `npm run generate:types:raw`.",
			" * Do not edit manually.",
			" ",
		].join("\n"),
		true,
	);

	return headerStatement;
}

function createNamedImport(
	moduleSpecifier: string,
	names: string[],
	useTypeSpecifiers: boolean,
): ts.ImportDeclaration {
	return ts.factory.createImportDeclaration(
		undefined,
		ts.factory.createImportClause(
			undefined,
			undefined,
			ts.factory.createNamedImports(
				names.map((name) =>
					ts.factory.createImportSpecifier(
						useTypeSpecifiers,
						undefined,
						ts.factory.createIdentifier(name),
					),
				),
			),
		),
		ts.factory.createStringLiteral(moduleSpecifier),
		undefined,
	);
}

function createDefaultedTypeParameter(
	name: string,
	constraint: ts.TypeNode,
): ts.TypeParameterDeclaration {
	return ts.factory.createTypeParameterDeclaration(
		undefined,
		ts.factory.createIdentifier(name),
		constraint,
		constraint,
	);
}

function createStatements({
	aliasBase,
	httpOperationApiErrorModuleSpecifier,
	httpOperationInferenceModuleSpecifier,
	operationIdentifier,
	sourceFile,
}: OperationStatementsTemplate): ts.Statement[] {
	const operationTypeName = `${aliasBase}Operation`;
	const operationTypeReference = ts.factory.createTypeReferenceNode(
		ts.factory.createIdentifier(operationTypeName),
		undefined,
	);

	return [
		createFileHeaderComment(sourceFile),
		createNamedImport(
			httpOperationApiErrorModuleSpecifier,
			["OperationApiError"],
			true,
		),
		createNamedImport(
			httpOperationInferenceModuleSpecifier,
			[
				"HttpOperationErrorBody",
				"HttpOperationErrorStatus",
				"HttpOperationPreferredRequest",
				"HttpOperationRequestInput",
				"HttpOperationResponseByStatus",
				"HttpOperationResponseStatus",
				"HttpOperationSuccessResponse",
			],
			true,
		),
		createNamedImport("./operation", [operationIdentifier], true),
		createExportedTypeAlias(
			operationTypeName,
			ts.factory.createTypeQueryNode(
				ts.factory.createIdentifier(operationIdentifier),
			),
		),
		createExportedTypeAlias(
			`${aliasBase}Request`,
			createTypeReference("HttpOperationPreferredRequest", [
				operationTypeReference,
			]),
		),
		createExportedTypeAlias(
			`${aliasBase}RequestParts`,
			createTypeReference("HttpOperationRequestInput", [
				operationTypeReference,
			]),
		),
		createExportedTypeAlias(
			`${aliasBase}SuccessResponse`,
			createTypeReference("HttpOperationSuccessResponse", [
				operationTypeReference,
			]),
		),
		createExportedTypeAlias(
			`${aliasBase}ResponseStatus`,
			createTypeReference("HttpOperationResponseStatus", [
				operationTypeReference,
			]),
		),
		createExportedTypeAlias(
			`${aliasBase}ErrorStatus`,
			createTypeReference("HttpOperationErrorStatus", [operationTypeReference]),
		),
		createExportedTypeAlias(
			`${aliasBase}ResponseByStatus`,
			createTypeReference("HttpOperationResponseByStatus", [
				operationTypeReference,
				ts.factory.createTypeReferenceNode(
					ts.factory.createIdentifier("TStatus"),
					undefined,
				),
			]),
			[
				createDefaultedTypeParameter(
					"TStatus",
					ts.factory.createTypeReferenceNode(
						ts.factory.createIdentifier(`${aliasBase}ResponseStatus`),
						undefined,
					),
				),
			],
		),
		createExportedTypeAlias(
			`${aliasBase}ApiError`,
			createTypeReference("OperationApiError", [
				operationTypeReference,
				ts.factory.createTypeReferenceNode(
					ts.factory.createIdentifier("TStatus"),
					undefined,
				),
			]),
			[
				createDefaultedTypeParameter(
					"TStatus",
					ts.factory.createTypeReferenceNode(
						ts.factory.createIdentifier(`${aliasBase}ErrorStatus`),
						undefined,
					),
				),
			],
		),
		createExportedTypeAlias(
			`${aliasBase}ErrorResponseBody`,
			createTypeReference("HttpOperationErrorBody", [
				operationTypeReference,
				ts.factory.createTypeReferenceNode(
					ts.factory.createIdentifier("TStatus"),
					undefined,
				),
			]),
			[
				createDefaultedTypeParameter(
					"TStatus",
					ts.factory.createTypeReferenceNode(
						ts.factory.createIdentifier(`${aliasBase}ErrorStatus`),
						undefined,
					),
				),
			],
		),
	];
}

function renderTypesFile({
	aliasBase,
	httpOperationApiErrorModuleSpecifier,
	httpOperationInferenceModuleSpecifier,
	operationIdentifier,
}: RenderTypesTemplate): string {
	const sourceFile = ts.createSourceFile(
		"types.ts",
		"",
		ts.ScriptTarget.Latest,
		false,
		ts.ScriptKind.TS,
	);
	const printer = ts.createPrinter({
		newLine: ts.NewLineKind.LineFeed,
	});
	const statements = createStatements({
		aliasBase,
		httpOperationApiErrorModuleSpecifier,
		httpOperationInferenceModuleSpecifier,
		operationIdentifier,
		sourceFile,
	});
	const printedStatements = statements
		.map((statement) =>
			printer.printNode(ts.EmitHint.Unspecified, statement, sourceFile),
		)
		.join("\n\n");

	return `${printedStatements}\n`;
}

function getPropertyNameText(name: ts.PropertyName): string | undefined {
	if (
		ts.isIdentifier(name) ||
		ts.isStringLiteral(name) ||
		ts.isNumericLiteral(name)
	) {
		return name.text;
	}

	return undefined;
}

function hasResponsesObject(
	operationDeclaration: OperationDeclaration,
): boolean {
	const configArgument = operationDeclaration.initializer.arguments[0];
	const operationIdentifier = ts.idText(operationDeclaration.name);

	if (
		configArgument == undefined ||
		!ts.isObjectLiteralExpression(configArgument)
	) {
		throw new Error(
			`Operation "${operationIdentifier}" is missing its config object`,
		);
	}

	const responsesProperty = configArgument.properties.find(
		(property): property is ts.PropertyAssignment =>
			ts.isPropertyAssignment(property) &&
			getPropertyNameText(property.name) === "responses",
	);

	if (
		responsesProperty == undefined ||
		!ts.isObjectLiteralExpression(responsesProperty.initializer)
	) {
		throw new Error(
			`Operation "${operationIdentifier}" must define a responses object`,
		);
	}

	return responsesProperty.initializer.properties.some((property) => {
		if (!ts.isPropertyAssignment(property)) {
			return false;
		}

		const statusText = getPropertyNameText(property.name);

		if (statusText == undefined) {
			return false;
		}

		return Number.isInteger(Number(statusText));
	});
}

function isDefineHttpOperationCall(
	initializer: ts.Expression | undefined,
): initializer is ts.CallExpression {
	return (
		initializer != undefined &&
		ts.isCallExpression(initializer) &&
		ts.isIdentifier(initializer.expression) &&
		initializer.expression.text === "defineHttpOperation"
	);
}

function hasExportModifier(statement: ts.Statement): boolean {
	if (!ts.canHaveModifiers(statement)) {
		return false;
	}

	for (const modifier of ts.getModifiers(statement) ?? []) {
		if (modifier.kind === ts.SyntaxKind.ExportKeyword) {
			return true;
		}
	}

	return false;
}

function findOperationDeclaration(
	sourceFile: ts.SourceFile,
): OperationDeclaration | undefined {
	for (const statement of sourceFile.statements) {
		if (!ts.isVariableStatement(statement) || !hasExportModifier(statement)) {
			continue;
		}

		for (const declaration of statement.declarationList.declarations) {
			if (
				ts.isIdentifier(declaration.name) &&
				isDefineHttpOperationCall(declaration.initializer)
			) {
				return {
					initializer: declaration.initializer,
					name: declaration.name,
				};
			}
		}
	}

	return undefined;
}

function capitalize(value: string): string {
	if (value.length === 0) {
		return value;
	}

	const [firstCharacter = ""] = value;

	return `${firstCharacter.toUpperCase()}${value.slice(1)}`;
}

function getRelativeModuleSpecifier(
	fromFilePath: string,
	targetPath: string,
): string {
	const relativePath = path.relative(path.dirname(fromFilePath), targetPath);
	const normalizedPath = relativePath
		.split(path.sep)
		.join("/")
		.replace(/\.[^./]+$/, "");

	if (normalizedPath.length === 0) {
		return ".";
	}

	return normalizedPath.startsWith(".")
		? normalizedPath
		: `./${normalizedPath}`;
}

function getErrorMessage(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}

function formatGenerationError(operationPath: string, error: unknown): string {
	const relativeOperationPath = path.relative(projectRoot, operationPath);

	return `Failed to generate types for ${relativeOperationPath}: ${getErrorMessage(error)}`;
}

function formatWriteError(typesPath: string, error: unknown): string {
	const relativeTypesPath = path.relative(projectRoot, typesPath);

	return `Failed to write ${relativeTypesPath}: ${getErrorMessage(error)}`;
}

function extractTemplate(operationPath: string): OperationTypesTemplate {
	const sourceText = fs.readFileSync(operationPath, "utf-8");
	const sourceFile = ts.createSourceFile(
		operationPath,
		sourceText,
		ts.ScriptTarget.Latest,
		true,
		ts.ScriptKind.TS,
	);
	const operationDeclaration = findOperationDeclaration(sourceFile);

	if (operationDeclaration == undefined) {
		throw new Error(
			`Could not find exported defineHttpOperation declaration in ${operationPath}`,
		);
	}

	const operationIdentifier = ts.idText(operationDeclaration.name);

	if (!operationIdentifier.endsWith(operationSuffix)) {
		throw new Error(
			`Expected operation variable to end with "Operation", got "${operationIdentifier}"`,
		);
	}

	if (!hasResponsesObject(operationDeclaration)) {
		throw new Error(
			`Operation "${operationIdentifier}" does not define responses`,
		);
	}

	return {
		aliasBase: capitalize(
			operationIdentifier.slice(0, -operationSuffix.length),
		),
		operationIdentifier,
	};
}

function discoverOperationPaths(rootDir: string): string[] {
	const paths: string[] = [];

	for (const entry of fs.readdirSync(rootDir, { withFileTypes: true })) {
		const entryPath = path.join(rootDir, entry.name);

		if (entry.isDirectory()) {
			paths.push(...discoverOperationPaths(entryPath));
			continue;
		}

		if (entry.isFile() && entry.name === "operation.ts") {
			paths.push(entryPath);
		}
	}

	// oxlint-disable-next-line unicorn/no-array-sort -- preserve toSorted semantics
	return [...paths].sort((left, right) => left.localeCompare(right));
}

function main(): void {
	const operationPaths = discoverOperationPaths(apiRoot);

	if (operationPaths.length === 0) {
		throw new Error(`No operation.ts files found under ${apiRoot}`);
	}

	const generatedFiles: GeneratedTypesFile[] = [];
	const errors: string[] = [];
	let writtenCount = 0;
	let unchangedCount = 0;

	for (const operationPath of operationPaths) {
		try {
			const template = extractTemplate(operationPath);
			const typesPath = path.join(path.dirname(operationPath), "types.ts");
			const nextContent = renderTypesFile({
				...template,
				httpOperationApiErrorModuleSpecifier: getRelativeModuleSpecifier(
					typesPath,
					httpOperationApiErrorPath,
				),
				httpOperationInferenceModuleSpecifier: getRelativeModuleSpecifier(
					typesPath,
					httpOperationInferencePath,
				),
			});
			const previousContent = fs.existsSync(typesPath)
				? fs.readFileSync(typesPath, "utf-8")
				: undefined;

			generatedFiles.push({
				nextContent,
				previousContent,
				typesPath,
			});
		} catch (error) {
			errors.push(formatGenerationError(operationPath, error));
		}
	}

	for (const { nextContent, previousContent, typesPath } of generatedFiles) {
		try {
			if (previousContent === nextContent) {
				unchangedCount += 1;
				continue;
			}

			fs.writeFileSync(typesPath, nextContent, "utf-8");
			writtenCount += 1;
		} catch (error) {
			errors.push(formatWriteError(typesPath, error));
		}
	}

	const summary = `Generated operation types for ${operationPaths.length} endpoints (${writtenCount} updated, ${unchangedCount} unchanged, ${errors.length} errors).`;

	if (errors.length > 0) {
		console.error("Operation type generation encountered errors:");

		for (const error of errors) {
			console.error(`- ${error}`);
		}

		console.error(summary);
		process.exitCode = 1;
		return;
	}

	console.log(summary);
}

main();
