/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type bannersListOperation } from "./operation";

export type BannersListOperation = typeof bannersListOperation;

export type BannersListRequest =
	HttpOperationPreferredRequest<BannersListOperation>;

export type BannersListRequestParts =
	HttpOperationRequestInput<BannersListOperation>;

export type BannersListSuccessResponse =
	HttpOperationSuccessResponse<BannersListOperation>;

export type BannersListResponseStatus =
	HttpOperationResponseStatus<BannersListOperation>;

export type BannersListErrorStatus =
	HttpOperationErrorStatus<BannersListOperation>;

export type BannersListResponseByStatus<
	TStatus extends BannersListResponseStatus = BannersListResponseStatus,
> = HttpOperationResponseByStatus<BannersListOperation, TStatus>;

export type BannersListApiError<
	TStatus extends BannersListErrorStatus = BannersListErrorStatus,
> = OperationApiError<BannersListOperation, TStatus>;

export type BannersListErrorResponseBody<
	TStatus extends BannersListErrorStatus = BannersListErrorStatus,
> = HttpOperationErrorBody<BannersListOperation, TStatus>;
