/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type shopsGetOperation } from "./operation";

export type ShopsGetOperation = typeof shopsGetOperation;

export type ShopsGetRequest = HttpOperationPreferredRequest<ShopsGetOperation>;

export type ShopsGetRequestParts = HttpOperationRequestInput<ShopsGetOperation>;

export type ShopsGetSuccessResponse =
	HttpOperationSuccessResponse<ShopsGetOperation>;

export type ShopsGetResponseStatus =
	HttpOperationResponseStatus<ShopsGetOperation>;

export type ShopsGetErrorStatus = HttpOperationErrorStatus<ShopsGetOperation>;

export type ShopsGetResponseByStatus<
	TStatus extends ShopsGetResponseStatus = ShopsGetResponseStatus,
> = HttpOperationResponseByStatus<ShopsGetOperation, TStatus>;

export type ShopsGetApiError<
	TStatus extends ShopsGetErrorStatus = ShopsGetErrorStatus,
> = OperationApiError<ShopsGetOperation, TStatus>;

export type ShopsGetErrorResponseBody<
	TStatus extends ShopsGetErrorStatus = ShopsGetErrorStatus,
> = HttpOperationErrorBody<ShopsGetOperation, TStatus>;
