/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type productsListOperation } from "./operation";

export type ProductsListOperation = typeof productsListOperation;

export type ProductsListRequest =
	HttpOperationPreferredRequest<ProductsListOperation>;

export type ProductsListRequestParts =
	HttpOperationRequestInput<ProductsListOperation>;

export type ProductsListSuccessResponse =
	HttpOperationSuccessResponse<ProductsListOperation>;

export type ProductsListResponseStatus =
	HttpOperationResponseStatus<ProductsListOperation>;

export type ProductsListErrorStatus =
	HttpOperationErrorStatus<ProductsListOperation>;

export type ProductsListResponseByStatus<
	TStatus extends ProductsListResponseStatus = ProductsListResponseStatus,
> = HttpOperationResponseByStatus<ProductsListOperation, TStatus>;

export type ProductsListApiError<
	TStatus extends ProductsListErrorStatus = ProductsListErrorStatus,
> = OperationApiError<ProductsListOperation, TStatus>;

export type ProductsListErrorResponseBody<
	TStatus extends ProductsListErrorStatus = ProductsListErrorStatus,
> = HttpOperationErrorBody<ProductsListOperation, TStatus>;
