/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type shopsGetMonobrandOperation } from "./operation";

export type ShopsGetMonobrandOperation = typeof shopsGetMonobrandOperation;

export type ShopsGetMonobrandRequest =
	HttpOperationPreferredRequest<ShopsGetMonobrandOperation>;

export type ShopsGetMonobrandRequestParts =
	HttpOperationRequestInput<ShopsGetMonobrandOperation>;

export type ShopsGetMonobrandSuccessResponse =
	HttpOperationSuccessResponse<ShopsGetMonobrandOperation>;

export type ShopsGetMonobrandResponseStatus =
	HttpOperationResponseStatus<ShopsGetMonobrandOperation>;

export type ShopsGetMonobrandErrorStatus =
	HttpOperationErrorStatus<ShopsGetMonobrandOperation>;

export type ShopsGetMonobrandResponseByStatus<
	TStatus extends ShopsGetMonobrandResponseStatus =
		ShopsGetMonobrandResponseStatus,
> = HttpOperationResponseByStatus<ShopsGetMonobrandOperation, TStatus>;

export type ShopsGetMonobrandApiError<
	TStatus extends ShopsGetMonobrandErrorStatus = ShopsGetMonobrandErrorStatus,
> = OperationApiError<ShopsGetMonobrandOperation, TStatus>;

export type ShopsGetMonobrandErrorResponseBody<
	TStatus extends ShopsGetMonobrandErrorStatus = ShopsGetMonobrandErrorStatus,
> = HttpOperationErrorBody<ShopsGetMonobrandOperation, TStatus>;
