/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type collectionsGetOperation } from "./operation";

export type CollectionsGetOperation = typeof collectionsGetOperation;

export type CollectionsGetRequest =
	HttpOperationPreferredRequest<CollectionsGetOperation>;

export type CollectionsGetRequestParts =
	HttpOperationRequestInput<CollectionsGetOperation>;

export type CollectionsGetSuccessResponse =
	HttpOperationSuccessResponse<CollectionsGetOperation>;

export type CollectionsGetResponseStatus =
	HttpOperationResponseStatus<CollectionsGetOperation>;

export type CollectionsGetErrorStatus =
	HttpOperationErrorStatus<CollectionsGetOperation>;

export type CollectionsGetResponseByStatus<
	TStatus extends CollectionsGetResponseStatus = CollectionsGetResponseStatus,
> = HttpOperationResponseByStatus<CollectionsGetOperation, TStatus>;

export type CollectionsGetApiError<
	TStatus extends CollectionsGetErrorStatus = CollectionsGetErrorStatus,
> = OperationApiError<CollectionsGetOperation, TStatus>;

export type CollectionsGetErrorResponseBody<
	TStatus extends CollectionsGetErrorStatus = CollectionsGetErrorStatus,
> = HttpOperationErrorBody<CollectionsGetOperation, TStatus>;
