/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type authLoginOperation } from "./operation";

export type AuthLoginOperation = typeof authLoginOperation;

export type AuthLoginRequest =
	HttpOperationPreferredRequest<AuthLoginOperation>;

export type AuthLoginRequestParts =
	HttpOperationRequestInput<AuthLoginOperation>;

export type AuthLoginSuccessResponse =
	HttpOperationSuccessResponse<AuthLoginOperation>;

export type AuthLoginResponseStatus =
	HttpOperationResponseStatus<AuthLoginOperation>;

export type AuthLoginErrorStatus = HttpOperationErrorStatus<AuthLoginOperation>;

export type AuthLoginResponseByStatus<
	TStatus extends AuthLoginResponseStatus = AuthLoginResponseStatus,
> = HttpOperationResponseByStatus<AuthLoginOperation, TStatus>;

export type AuthLoginApiError<
	TStatus extends AuthLoginErrorStatus = AuthLoginErrorStatus,
> = OperationApiError<AuthLoginOperation, TStatus>;

export type AuthLoginErrorResponseBody<
	TStatus extends AuthLoginErrorStatus = AuthLoginErrorStatus,
> = HttpOperationErrorBody<AuthLoginOperation, TStatus>;
