/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type skuGetSimilarOperation } from "./operation";

export type SkuGetSimilarOperation = typeof skuGetSimilarOperation;

export type SkuGetSimilarRequest =
	HttpOperationPreferredRequest<SkuGetSimilarOperation>;

export type SkuGetSimilarRequestParts =
	HttpOperationRequestInput<SkuGetSimilarOperation>;

export type SkuGetSimilarSuccessResponse =
	HttpOperationSuccessResponse<SkuGetSimilarOperation>;

export type SkuGetSimilarResponseStatus =
	HttpOperationResponseStatus<SkuGetSimilarOperation>;

export type SkuGetSimilarErrorStatus =
	HttpOperationErrorStatus<SkuGetSimilarOperation>;

export type SkuGetSimilarResponseByStatus<
	TStatus extends SkuGetSimilarResponseStatus = SkuGetSimilarResponseStatus,
> = HttpOperationResponseByStatus<SkuGetSimilarOperation, TStatus>;

export type SkuGetSimilarApiError<
	TStatus extends SkuGetSimilarErrorStatus = SkuGetSimilarErrorStatus,
> = OperationApiError<SkuGetSimilarOperation, TStatus>;

export type SkuGetSimilarErrorResponseBody<
	TStatus extends SkuGetSimilarErrorStatus = SkuGetSimilarErrorStatus,
> = HttpOperationErrorBody<SkuGetSimilarOperation, TStatus>;
