/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type skuGetReviewAvailableOperation } from "./operation";

export type SkuGetReviewAvailableOperation =
	typeof skuGetReviewAvailableOperation;

export type SkuGetReviewAvailableRequest =
	HttpOperationPreferredRequest<SkuGetReviewAvailableOperation>;

export type SkuGetReviewAvailableRequestParts =
	HttpOperationRequestInput<SkuGetReviewAvailableOperation>;

export type SkuGetReviewAvailableSuccessResponse =
	HttpOperationSuccessResponse<SkuGetReviewAvailableOperation>;

export type SkuGetReviewAvailableResponseStatus =
	HttpOperationResponseStatus<SkuGetReviewAvailableOperation>;

export type SkuGetReviewAvailableErrorStatus =
	HttpOperationErrorStatus<SkuGetReviewAvailableOperation>;

export type SkuGetReviewAvailableResponseByStatus<
	TStatus extends SkuGetReviewAvailableResponseStatus =
		SkuGetReviewAvailableResponseStatus,
> = HttpOperationResponseByStatus<SkuGetReviewAvailableOperation, TStatus>;

export type SkuGetReviewAvailableApiError<
	TStatus extends SkuGetReviewAvailableErrorStatus =
		SkuGetReviewAvailableErrorStatus,
> = OperationApiError<SkuGetReviewAvailableOperation, TStatus>;

export type SkuGetReviewAvailableErrorResponseBody<
	TStatus extends SkuGetReviewAvailableErrorStatus =
		SkuGetReviewAvailableErrorStatus,
> = HttpOperationErrorBody<SkuGetReviewAvailableOperation, TStatus>;
