/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type shopsGetProductsOperation } from "./operation";

export type ShopsGetProductsOperation = typeof shopsGetProductsOperation;

export type ShopsGetProductsRequest =
	HttpOperationPreferredRequest<ShopsGetProductsOperation>;

export type ShopsGetProductsRequestParts =
	HttpOperationRequestInput<ShopsGetProductsOperation>;

export type ShopsGetProductsSuccessResponse =
	HttpOperationSuccessResponse<ShopsGetProductsOperation>;

export type ShopsGetProductsResponseStatus =
	HttpOperationResponseStatus<ShopsGetProductsOperation>;

export type ShopsGetProductsErrorStatus =
	HttpOperationErrorStatus<ShopsGetProductsOperation>;

export type ShopsGetProductsResponseByStatus<
	TStatus extends ShopsGetProductsResponseStatus =
		ShopsGetProductsResponseStatus,
> = HttpOperationResponseByStatus<ShopsGetProductsOperation, TStatus>;

export type ShopsGetProductsApiError<
	TStatus extends ShopsGetProductsErrorStatus = ShopsGetProductsErrorStatus,
> = OperationApiError<ShopsGetProductsOperation, TStatus>;

export type ShopsGetProductsErrorResponseBody<
	TStatus extends ShopsGetProductsErrorStatus = ShopsGetProductsErrorStatus,
> = HttpOperationErrorBody<ShopsGetProductsOperation, TStatus>;
