/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type collectionsListOperation } from "./operation";

export type CollectionsListOperation = typeof collectionsListOperation;

export type CollectionsListRequest =
	HttpOperationPreferredRequest<CollectionsListOperation>;

export type CollectionsListRequestParts =
	HttpOperationRequestInput<CollectionsListOperation>;

export type CollectionsListSuccessResponse =
	HttpOperationSuccessResponse<CollectionsListOperation>;

export type CollectionsListResponseStatus =
	HttpOperationResponseStatus<CollectionsListOperation>;

export type CollectionsListErrorStatus =
	HttpOperationErrorStatus<CollectionsListOperation>;

export type CollectionsListResponseByStatus<
	TStatus extends CollectionsListResponseStatus = CollectionsListResponseStatus,
> = HttpOperationResponseByStatus<CollectionsListOperation, TStatus>;

export type CollectionsListApiError<
	TStatus extends CollectionsListErrorStatus = CollectionsListErrorStatus,
> = OperationApiError<CollectionsListOperation, TStatus>;

export type CollectionsListErrorResponseBody<
	TStatus extends CollectionsListErrorStatus = CollectionsListErrorStatus,
> = HttpOperationErrorBody<CollectionsListOperation, TStatus>;
