/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type featureFlagsListOperation } from "./operation";

export type FeatureFlagsListOperation = typeof featureFlagsListOperation;

export type FeatureFlagsListRequest =
	HttpOperationPreferredRequest<FeatureFlagsListOperation>;

export type FeatureFlagsListRequestParts =
	HttpOperationRequestInput<FeatureFlagsListOperation>;

export type FeatureFlagsListSuccessResponse =
	HttpOperationSuccessResponse<FeatureFlagsListOperation>;

export type FeatureFlagsListResponseStatus =
	HttpOperationResponseStatus<FeatureFlagsListOperation>;

export type FeatureFlagsListErrorStatus =
	HttpOperationErrorStatus<FeatureFlagsListOperation>;

export type FeatureFlagsListResponseByStatus<
	TStatus extends FeatureFlagsListResponseStatus =
		FeatureFlagsListResponseStatus,
> = HttpOperationResponseByStatus<FeatureFlagsListOperation, TStatus>;

export type FeatureFlagsListApiError<
	TStatus extends FeatureFlagsListErrorStatus = FeatureFlagsListErrorStatus,
> = OperationApiError<FeatureFlagsListOperation, TStatus>;

export type FeatureFlagsListErrorResponseBody<
	TStatus extends FeatureFlagsListErrorStatus = FeatureFlagsListErrorStatus,
> = HttpOperationErrorBody<FeatureFlagsListOperation, TStatus>;
