/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type categoriesGetParentsOperation } from "./operation";

export type CategoriesGetParentsOperation =
	typeof categoriesGetParentsOperation;

export type CategoriesGetParentsRequest =
	HttpOperationPreferredRequest<CategoriesGetParentsOperation>;

export type CategoriesGetParentsRequestParts =
	HttpOperationRequestInput<CategoriesGetParentsOperation>;

export type CategoriesGetParentsSuccessResponse =
	HttpOperationSuccessResponse<CategoriesGetParentsOperation>;

export type CategoriesGetParentsResponseStatus =
	HttpOperationResponseStatus<CategoriesGetParentsOperation>;

export type CategoriesGetParentsErrorStatus =
	HttpOperationErrorStatus<CategoriesGetParentsOperation>;

export type CategoriesGetParentsResponseByStatus<
	TStatus extends CategoriesGetParentsResponseStatus =
		CategoriesGetParentsResponseStatus,
> = HttpOperationResponseByStatus<CategoriesGetParentsOperation, TStatus>;

export type CategoriesGetParentsApiError<
	TStatus extends CategoriesGetParentsErrorStatus =
		CategoriesGetParentsErrorStatus,
> = OperationApiError<CategoriesGetParentsOperation, TStatus>;

export type CategoriesGetParentsErrorResponseBody<
	TStatus extends CategoriesGetParentsErrorStatus =
		CategoriesGetParentsErrorStatus,
> = HttpOperationErrorBody<CategoriesGetParentsOperation, TStatus>;
