/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type skuGetOperation } from "./operation";

export type SkuGetOperation = typeof skuGetOperation;

export type SkuGetRequest = HttpOperationPreferredRequest<SkuGetOperation>;

export type SkuGetRequestParts = HttpOperationRequestInput<SkuGetOperation>;

export type SkuGetSuccessResponse =
	HttpOperationSuccessResponse<SkuGetOperation>;

export type SkuGetResponseStatus = HttpOperationResponseStatus<SkuGetOperation>;

export type SkuGetErrorStatus = HttpOperationErrorStatus<SkuGetOperation>;

export type SkuGetResponseByStatus<
	TStatus extends SkuGetResponseStatus = SkuGetResponseStatus,
> = HttpOperationResponseByStatus<SkuGetOperation, TStatus>;

export type SkuGetApiError<
	TStatus extends SkuGetErrorStatus = SkuGetErrorStatus,
> = OperationApiError<SkuGetOperation, TStatus>;

export type SkuGetErrorResponseBody<
	TStatus extends SkuGetErrorStatus = SkuGetErrorStatus,
> = HttpOperationErrorBody<SkuGetOperation, TStatus>;
