/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type productsAutocompleteOperation } from "./operation";

export type ProductsAutocompleteOperation =
	typeof productsAutocompleteOperation;

export type ProductsAutocompleteRequest =
	HttpOperationPreferredRequest<ProductsAutocompleteOperation>;

export type ProductsAutocompleteRequestParts =
	HttpOperationRequestInput<ProductsAutocompleteOperation>;

export type ProductsAutocompleteSuccessResponse =
	HttpOperationSuccessResponse<ProductsAutocompleteOperation>;

export type ProductsAutocompleteResponseStatus =
	HttpOperationResponseStatus<ProductsAutocompleteOperation>;

export type ProductsAutocompleteErrorStatus =
	HttpOperationErrorStatus<ProductsAutocompleteOperation>;

export type ProductsAutocompleteResponseByStatus<
	TStatus extends ProductsAutocompleteResponseStatus =
		ProductsAutocompleteResponseStatus,
> = HttpOperationResponseByStatus<ProductsAutocompleteOperation, TStatus>;

export type ProductsAutocompleteApiError<
	TStatus extends ProductsAutocompleteErrorStatus =
		ProductsAutocompleteErrorStatus,
> = OperationApiError<ProductsAutocompleteOperation, TStatus>;

export type ProductsAutocompleteErrorResponseBody<
	TStatus extends ProductsAutocompleteErrorStatus =
		ProductsAutocompleteErrorStatus,
> = HttpOperationErrorBody<ProductsAutocompleteOperation, TStatus>;
