/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type favoritesAddOperation } from "./operation";

export type FavoritesAddOperation = typeof favoritesAddOperation;

export type FavoritesAddRequest =
	HttpOperationPreferredRequest<FavoritesAddOperation>;

export type FavoritesAddRequestParts =
	HttpOperationRequestInput<FavoritesAddOperation>;

export type FavoritesAddSuccessResponse =
	HttpOperationSuccessResponse<FavoritesAddOperation>;

export type FavoritesAddResponseStatus =
	HttpOperationResponseStatus<FavoritesAddOperation>;

export type FavoritesAddErrorStatus =
	HttpOperationErrorStatus<FavoritesAddOperation>;

export type FavoritesAddResponseByStatus<
	TStatus extends FavoritesAddResponseStatus = FavoritesAddResponseStatus,
> = HttpOperationResponseByStatus<FavoritesAddOperation, TStatus>;

export type FavoritesAddApiError<
	TStatus extends FavoritesAddErrorStatus = FavoritesAddErrorStatus,
> = OperationApiError<FavoritesAddOperation, TStatus>;

export type FavoritesAddErrorResponseBody<
	TStatus extends FavoritesAddErrorStatus = FavoritesAddErrorStatus,
> = HttpOperationErrorBody<FavoritesAddOperation, TStatus>;
