/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type categoriesListOperation } from "./operation";

export type CategoriesListOperation = typeof categoriesListOperation;

export type CategoriesListRequest =
	HttpOperationPreferredRequest<CategoriesListOperation>;

export type CategoriesListRequestParts =
	HttpOperationRequestInput<CategoriesListOperation>;

export type CategoriesListSuccessResponse =
	HttpOperationSuccessResponse<CategoriesListOperation>;

export type CategoriesListResponseStatus =
	HttpOperationResponseStatus<CategoriesListOperation>;

export type CategoriesListErrorStatus =
	HttpOperationErrorStatus<CategoriesListOperation>;

export type CategoriesListResponseByStatus<
	TStatus extends CategoriesListResponseStatus = CategoriesListResponseStatus,
> = HttpOperationResponseByStatus<CategoriesListOperation, TStatus>;

export type CategoriesListApiError<
	TStatus extends CategoriesListErrorStatus = CategoriesListErrorStatus,
> = OperationApiError<CategoriesListOperation, TStatus>;

export type CategoriesListErrorResponseBody<
	TStatus extends CategoriesListErrorStatus = CategoriesListErrorStatus,
> = HttpOperationErrorBody<CategoriesListOperation, TStatus>;
