/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type usersUpdateLanguageOperation } from "./operation";

export type UsersUpdateLanguageOperation = typeof usersUpdateLanguageOperation;

export type UsersUpdateLanguageRequest =
	HttpOperationPreferredRequest<UsersUpdateLanguageOperation>;

export type UsersUpdateLanguageRequestParts =
	HttpOperationRequestInput<UsersUpdateLanguageOperation>;

export type UsersUpdateLanguageSuccessResponse =
	HttpOperationSuccessResponse<UsersUpdateLanguageOperation>;

export type UsersUpdateLanguageResponseStatus =
	HttpOperationResponseStatus<UsersUpdateLanguageOperation>;

export type UsersUpdateLanguageErrorStatus =
	HttpOperationErrorStatus<UsersUpdateLanguageOperation>;

export type UsersUpdateLanguageResponseByStatus<
	TStatus extends UsersUpdateLanguageResponseStatus =
		UsersUpdateLanguageResponseStatus,
> = HttpOperationResponseByStatus<UsersUpdateLanguageOperation, TStatus>;

export type UsersUpdateLanguageApiError<
	TStatus extends UsersUpdateLanguageErrorStatus =
		UsersUpdateLanguageErrorStatus,
> = OperationApiError<UsersUpdateLanguageOperation, TStatus>;

export type UsersUpdateLanguageErrorResponseBody<
	TStatus extends UsersUpdateLanguageErrorStatus =
		UsersUpdateLanguageErrorStatus,
> = HttpOperationErrorBody<UsersUpdateLanguageOperation, TStatus>;
