/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type favoritesGetIdsOperation } from "./operation";

export type FavoritesGetIdsOperation = typeof favoritesGetIdsOperation;

export type FavoritesGetIdsRequest =
	HttpOperationPreferredRequest<FavoritesGetIdsOperation>;

export type FavoritesGetIdsRequestParts =
	HttpOperationRequestInput<FavoritesGetIdsOperation>;

export type FavoritesGetIdsSuccessResponse =
	HttpOperationSuccessResponse<FavoritesGetIdsOperation>;

export type FavoritesGetIdsResponseStatus =
	HttpOperationResponseStatus<FavoritesGetIdsOperation>;

export type FavoritesGetIdsErrorStatus =
	HttpOperationErrorStatus<FavoritesGetIdsOperation>;

export type FavoritesGetIdsResponseByStatus<
	TStatus extends FavoritesGetIdsResponseStatus = FavoritesGetIdsResponseStatus,
> = HttpOperationResponseByStatus<FavoritesGetIdsOperation, TStatus>;

export type FavoritesGetIdsApiError<
	TStatus extends FavoritesGetIdsErrorStatus = FavoritesGetIdsErrorStatus,
> = OperationApiError<FavoritesGetIdsOperation, TStatus>;

export type FavoritesGetIdsErrorResponseBody<
	TStatus extends FavoritesGetIdsErrorStatus = FavoritesGetIdsErrorStatus,
> = HttpOperationErrorBody<FavoritesGetIdsOperation, TStatus>;
