/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type collectionsGetSkusOperation } from "./operation";

export type CollectionsGetSkusOperation = typeof collectionsGetSkusOperation;

export type CollectionsGetSkusRequest =
	HttpOperationPreferredRequest<CollectionsGetSkusOperation>;

export type CollectionsGetSkusRequestParts =
	HttpOperationRequestInput<CollectionsGetSkusOperation>;

export type CollectionsGetSkusSuccessResponse =
	HttpOperationSuccessResponse<CollectionsGetSkusOperation>;

export type CollectionsGetSkusResponseStatus =
	HttpOperationResponseStatus<CollectionsGetSkusOperation>;

export type CollectionsGetSkusErrorStatus =
	HttpOperationErrorStatus<CollectionsGetSkusOperation>;

export type CollectionsGetSkusResponseByStatus<
	TStatus extends CollectionsGetSkusResponseStatus =
		CollectionsGetSkusResponseStatus,
> = HttpOperationResponseByStatus<CollectionsGetSkusOperation, TStatus>;

export type CollectionsGetSkusApiError<
	TStatus extends CollectionsGetSkusErrorStatus = CollectionsGetSkusErrorStatus,
> = OperationApiError<CollectionsGetSkusOperation, TStatus>;

export type CollectionsGetSkusErrorResponseBody<
	TStatus extends CollectionsGetSkusErrorStatus = CollectionsGetSkusErrorStatus,
> = HttpOperationErrorBody<CollectionsGetSkusOperation, TStatus>;
