/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type productsGetReviewsOperation } from "./operation";

export type ProductsGetReviewsOperation = typeof productsGetReviewsOperation;

export type ProductsGetReviewsRequest =
	HttpOperationPreferredRequest<ProductsGetReviewsOperation>;

export type ProductsGetReviewsRequestParts =
	HttpOperationRequestInput<ProductsGetReviewsOperation>;

export type ProductsGetReviewsSuccessResponse =
	HttpOperationSuccessResponse<ProductsGetReviewsOperation>;

export type ProductsGetReviewsResponseStatus =
	HttpOperationResponseStatus<ProductsGetReviewsOperation>;

export type ProductsGetReviewsErrorStatus =
	HttpOperationErrorStatus<ProductsGetReviewsOperation>;

export type ProductsGetReviewsResponseByStatus<
	TStatus extends ProductsGetReviewsResponseStatus =
		ProductsGetReviewsResponseStatus,
> = HttpOperationResponseByStatus<ProductsGetReviewsOperation, TStatus>;

export type ProductsGetReviewsApiError<
	TStatus extends ProductsGetReviewsErrorStatus = ProductsGetReviewsErrorStatus,
> = OperationApiError<ProductsGetReviewsOperation, TStatus>;

export type ProductsGetReviewsErrorResponseBody<
	TStatus extends ProductsGetReviewsErrorStatus = ProductsGetReviewsErrorStatus,
> = HttpOperationErrorBody<ProductsGetReviewsOperation, TStatus>;
