/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type categoriesGetOperation } from "./operation";

export type CategoriesGetOperation = typeof categoriesGetOperation;

export type CategoriesGetRequest =
	HttpOperationPreferredRequest<CategoriesGetOperation>;

export type CategoriesGetRequestParts =
	HttpOperationRequestInput<CategoriesGetOperation>;

export type CategoriesGetSuccessResponse =
	HttpOperationSuccessResponse<CategoriesGetOperation>;

export type CategoriesGetResponseStatus =
	HttpOperationResponseStatus<CategoriesGetOperation>;

export type CategoriesGetErrorStatus =
	HttpOperationErrorStatus<CategoriesGetOperation>;

export type CategoriesGetResponseByStatus<
	TStatus extends CategoriesGetResponseStatus = CategoriesGetResponseStatus,
> = HttpOperationResponseByStatus<CategoriesGetOperation, TStatus>;

export type CategoriesGetApiError<
	TStatus extends CategoriesGetErrorStatus = CategoriesGetErrorStatus,
> = OperationApiError<CategoriesGetOperation, TStatus>;

export type CategoriesGetErrorResponseBody<
	TStatus extends CategoriesGetErrorStatus = CategoriesGetErrorStatus,
> = HttpOperationErrorBody<CategoriesGetOperation, TStatus>;
