/**
 * This file is auto-generated by `npm run generate:types:raw`.
 * Do not edit manually.
 */

import { type OperationApiError } from "../../../http-operation/api-error";
import {
	type HttpOperationErrorBody,
	type HttpOperationErrorStatus,
	type HttpOperationPreferredRequest,
	type HttpOperationRequestInput,
	type HttpOperationResponseByStatus,
	type HttpOperationResponseStatus,
	type HttpOperationSuccessResponse,
} from "../../../http-operation/inference";
import { type authVerifyOperation } from "./operation";

export type AuthVerifyOperation = typeof authVerifyOperation;

export type AuthVerifyRequest =
	HttpOperationPreferredRequest<AuthVerifyOperation>;

export type AuthVerifyRequestParts =
	HttpOperationRequestInput<AuthVerifyOperation>;

export type AuthVerifySuccessResponse =
	HttpOperationSuccessResponse<AuthVerifyOperation>;

export type AuthVerifyResponseStatus =
	HttpOperationResponseStatus<AuthVerifyOperation>;

export type AuthVerifyErrorStatus =
	HttpOperationErrorStatus<AuthVerifyOperation>;

export type AuthVerifyResponseByStatus<
	TStatus extends AuthVerifyResponseStatus = AuthVerifyResponseStatus,
> = HttpOperationResponseByStatus<AuthVerifyOperation, TStatus>;

export type AuthVerifyApiError<
	TStatus extends AuthVerifyErrorStatus = AuthVerifyErrorStatus,
> = OperationApiError<AuthVerifyOperation, TStatus>;

export type AuthVerifyErrorResponseBody<
	TStatus extends AuthVerifyErrorStatus = AuthVerifyErrorStatus,
> = HttpOperationErrorBody<AuthVerifyOperation, TStatus>;
